// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udipesojingylaeersxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaXBlc29qaW5neWxhZWVyc3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODYwOTgsImV4cCI6MjA2NDQ2MjA5OH0.U-F8gmv5kN4Ehh79I1a0y1NRuJH4EDZQ2v8112mZXgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);